<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ATMECSINLT-085" ignored="0" name="Test validate IEHome" tests="1" failures="0" timestamp="22 Oct 2019 14:40:23 GMT" time="6.727" errors="0">
  <testcase name="@BeforeTest baseSetup" time="5.157" classname="org.atmecs.website.testbase.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at org.atmecs.website.testbase.TestBase.baseSetup(TestBase.java:85)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest baseSetup -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="org.atmecs.website.extentreports.Extent">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="footerValidate" time="0.0" classname="org.atmecs.website.testscripts.Home">
    <skipped/>
  </testcase> <!-- footerValidate -->
</testsuite> <!-- Test validate IEHome -->
